/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.46                          *
*        Compiled Dec 12 2017, 16:38:40                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "app.h"
#include "DIALOG.h"

WM_HWIN Createlpc55sxx_imx7ulp_faceid(void);

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0       (GUI_ID_USER + 0x01)
#define ID_SPINBOX_0      (GUI_ID_USER + 0x02)
#define ID_BUTTON_1       (GUI_ID_USER + 0x03)
#define ID_TEXT_0         (GUI_ID_USER + 0x05)
#define ID_IMAGE_0        (GUI_ID_USER + 0x06)
#define ID_IMAGE_1        (GUI_ID_USER + 0x07)

#define ID_IMAGE_0_IMAGE_0  0x00
#define ID_IMAGE_1_IMAGE_0  0x01

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Enroll_face", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,   "Back", ID_BUTTON_0, 142, 58, 80, 40, 0, 0x0, 0 },
//  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 24, 13, 80, 18, 0, 0x0, 0 },
  { BUTTON_CreateIndirect,   "Enroll", ID_BUTTON_1, 143, 9, 80, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect,     "Select FaceID's Num", ID_TEXT_0, 11, 18, 120, 20, 0, 0x0, 0 },
  { SPINBOX_CreateIndirect,  "Spinbox", ID_SPINBOX_0, 23, 47, 80, 45, 0, 0x0, 0 },
  { IMAGE_CreateIndirect,    "nxp_logo", ID_IMAGE_0, 125, 253, 100, 47, 0, 0, 0 },
  { IMAGE_CreateIndirect,    "face_logo", ID_IMAGE_1, 0, 102, 230, 200, 0, 0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/

static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  WM_HWIN hOldItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Enroll_face'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    FRAMEWIN_SetFont(hItem, GUI_FONT_6X8);
    //
    // Initialization of 'nxp_logo'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
    IMAGE_SetBitmap(hItem, &bmimage_nxplogo);

    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //PRINTF("Back Released\r\n");
        g_TestID = 0;
        Createlpc55sxx_imx7ulp_faceid();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Enroll'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //PRINTF("Enroll Released\r\n");
        g_TestID = 1;
#if 0        
        if(g_TestID == 0)
        {
            *(volatile uint16_t *)0x20043008 = 0x0000;
            *(volatile uint16_t *)0x20043004 = 0x55AA;
            GUI_X_Delay(10);
            while(*(volatile uint16_t *)0x20043008 != 0xA55A)
            {
            ;
            }
            hOldItem= WM_SelectWindow(WM_GetClientWindow(pMsg->hWin));
            GUI_SetColor(GUI_WHITE);
            GUI_FillRect(0, 105, 235, 310);
            //GUI_DrawBitmap(&bmui_face_big, 5, 107);
            GUI_DrawBitmap(&bmui_face_big, -55, 107);
            GUI_SetColor(GUI_RED);
            GUI_DrawCircle(120, 202, FACE_SIZE+1);
            GUI_DrawCircle(120, 202, FACE_SIZE);
            GUI_DrawCircle(120, 202, FACE_SIZE-1);
            WM_SelectWindow(hOldItem);
            *(volatile uint16_t *)0x20043004 = 0x0000;
            //
            g_TestID = 1;
        }
        else if(g_TestID == 1)
        {
            *(volatile uint16_t *)0x20043004 = 0x55AA;
            GUI_X_Delay(10);
            *(volatile uint16_t *)0x20043008 = 0x0000;
            *(volatile uint16_t *)0x20043004 = 0x55AA;
            GUI_X_Delay(10);
            while(*(volatile uint16_t *)0x20043008 != 0xA55A)
            {
            ;
            }
            hOldItem= WM_SelectWindow(WM_GetClientWindow(pMsg->hWin));
            GUI_SetColor(GUI_WHITE);
            GUI_FillRect(0, 105, 235, 310);
            GUI_DrawBitmap(&bmui_face_mid, 33, 130);
            GUI_SetColor(GUI_RED);
            GUI_DrawCircle(120, 202, FACE_SIZE+1);
            GUI_DrawCircle(120, 202, FACE_SIZE);
            GUI_DrawCircle(120, 202, FACE_SIZE-1);
            WM_SelectWindow(hOldItem);
            *(volatile uint16_t *)0x20043004 = 0x0000;
            g_TestID = 2;
        }
        else
        {
            *(volatile uint16_t *)0x20043004 = 0x55AA;
            GUI_X_Delay(10);
            *(volatile uint16_t *)0x20043008 = 0x0000;
            *(volatile uint16_t *)0x20043004 = 0x55AA;
            GUI_X_Delay(10);
            while(*(volatile uint16_t *)0x20043008 != 0xA55A)
            {
                ;
            }
            hOldItem= WM_SelectWindow(WM_GetClientWindow(pMsg->hWin));
            GUI_SetColor(GUI_WHITE);
            GUI_FillRect(0, 105, 235, 310);
            GUI_DrawBitmap(&bmui_face_little, 120, 202);
            GUI_SetColor(GUI_RED);
            GUI_DrawCircle(120, 202, FACE_SIZE+1);
            GUI_DrawCircle(120, 202, FACE_SIZE);
            GUI_DrawCircle(120, 202, FACE_SIZE-1);
            WM_SelectWindow(hOldItem);
            *(volatile uint16_t *)0x20043004 = 0x0000;
            g_TestID = 0;
        }
#endif
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    case ID_SPINBOX_0: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateEnroll_face
*/
WM_HWIN CreateEnroll_face(void);
WM_HWIN CreateEnroll_face(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
